### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by rolandgeider** [mozilla/django-browserid#291]
I just tried updating to the django 1.9 beta, but there's an import error:

```python
File "[snip]/local/lib/python2.7/site-packages/django_browserid/base.py", line 11, in <module>
    from django.utils.http import same_origin
ImportError: cannot import name same_origin
```

I could not find anything about ``same_origin`` in the release notes, perhaps this was a half-private helper?

**Comment by Osmose** [comment]
This should be fixed on master. Once 1.9 is released proper we'll do a bugfix release with 1.9 support officially. Thanks for finding this!

**Comment by cultavix** [comment]
I still get this., I'm running Django 1.9
<code>
  File "/usr/lib/python2.7/site-packages/mama_cas/models.py", line 14, in <module>
    from django.utils.http import same_origin
ImportError: cannot import name same_origin
</code>
